// 层：视图
#pragma once
#include <QObject>
#include <QString>
#include <QStringList>

#include <functional>

class QAction;
class QgsLayout;

// ui/layout — Task C: template library for the layout designer shell.
//
// Wraps QgsLayout::saveAsTemplate / loadFromTemplate (clearExisting=true) and
// ships two builtin families:
//   * page-setup .qpt files under docs/templates/ (generated by QgsPrintLayout
//     + saveAsTemplate, so they are guaranteed to round-trip through
//     loadFromTemplate): a4_landscape/a4_portrait/a3_landscape/a3_portrait/
//     a0_landscape.
//   * content-figure templates (方向 25)：三类图件骨架（井位图/单因素图/沉积相
//     图）× A4/A3 横竖，键形如 "well_position@a4_landscape"。内容走
//     PaleoStandardElements::populateFigureLayout 代码路径（不落 .qpt——骨架
//     与元素工厂单一事实源），页面规格在应用时解析。
//
// TemplateOutcome::itemCount counts *content* items (all QgsLayoutItems except
// QgsLayoutItemPage paper items) — the QGIS loadFromTemplate return value also
// drags in page items, which is not what a user means by "item count".
class PaleoLayoutTemplates : public QObject
{
    Q_OBJECT
  public:
    struct TemplateOutcome
    {
        bool ok = false;
        QString error;      //!< human-readable, empty on success
        int itemCount = 0;  //!< load/apply: content items after load; save: content items written
    };

    explicit PaleoLayoutTemplates( QObject *parent = nullptr );

    // User template files (.qpt). saveTemplate() = QgsLayout::saveAsTemplate;
    // loadTemplate() = file → QDomDocument → loadFromTemplate(clearExisting=true).
    TemplateOutcome saveTemplate( QgsLayout *layout, const QString &path );
    TemplateOutcome loadTemplate( QgsLayout *layout, const QString &path );

    // Builtin page-setup library (.qpt keys, in menu order).
    static QStringList builtinKeys();
    // Builtin content-figure kinds × page variants (composite keys, in menu order):
    // {well_position,single_factor,facies} × {a4_landscape,a4_portrait,a3_landscape,a3_portrait}.
    static QStringList figureBuiltinKeys();
    static QString builtinTitle( const QString &key ); //!< empty for unknown keys
    TemplateOutcome applyBuiltin( QgsLayout *layout, const QString &key );

    // Directory holding <key>.qpt builtins. Resolution order:
    //   1. the last value passed to setTemplatesDir() (empty resets to auto);
    //   2. $PALEO_LAYOUT_TEMPLATES_DIR;
    //   3. first existing "<app dir | ancestor up to 3 levels>/docs/templates".
    // Returns an empty string when nothing resolves — applyBuiltin then fails
    // with "not found" until the dir is set. Tests pin it to the worktree's
    // docs/templates explicitly.
    void setTemplatesDir( const QString &dir );
    QString templatesDir() const;

    // Actions for the shell's File menu.
    QAction *saveAsTemplateAction();
    QAction *loadFromTemplateAction();
    QAction *applyBuiltinAction( const QString &key ); //!< nullptr for unknown keys

    // UI wiring: layout provider consulted by the action handlers only.
    void setLayoutProvider( const std::function<QgsLayout *()> &provider );

  signals:
    void templateFinished( const QString &path, bool ok );

  private:
    TemplateOutcome loadFromFile( QgsLayout *layout, const QString &path );

    QAction *m_saveAction = nullptr;
    QAction *m_loadAction = nullptr;
    std::function<QgsLayout *()> m_layoutProvider;
    QString m_templatesDir;
};
