// 层：视图
#pragma once
#include <QObject>
#include <QString>
#include <QStringList>

#include <functional>

class QAction;
class QgsLayout;

// ui/layout — Task C: template library for the layout designer shell.
//
// Wraps QgsLayout::saveAsTemplate / loadFromTemplate (clearExisting=true) and
// ships three builtin page-setup templates as .qpt files under
// docs/templates/ (generated by QgsPrintLayout + saveAsTemplate, so they are
// guaranteed to round-trip through loadFromTemplate):
//   a4_landscape  297 × 210 mm
//   a4_portrait   210 × 297 mm
//   a0_landscape  1189 × 841 mm
//
// TemplateOutcome::itemCount counts *content* items (all QgsLayoutItems except
// QgsLayoutItemPage paper items) — the QGIS loadFromTemplate return value also
// drags in page items, which is not what a user means by "item count".
class PaleoLayoutTemplates : public QObject
{
    Q_OBJECT
  public:
    struct TemplateOutcome
    {
        bool ok = false;
        QString error;      //!< human-readable, empty on success
        int itemCount = 0;  //!< load/apply: content items after load; save: content items written
    };

    explicit PaleoLayoutTemplates( QObject *parent = nullptr );

    // User template files (.qpt). saveTemplate() = QgsLayout::saveAsTemplate;
    // loadTemplate() = file → QDomDocument → loadFromTemplate(clearExisting=true).
    TemplateOutcome saveTemplate( QgsLayout *layout, const QString &path );
    TemplateOutcome loadTemplate( QgsLayout *layout, const QString &path );

    // Builtin page-setup library.
    static QStringList builtinKeys();
    static QString builtinTitle( const QString &key ); //!< empty for unknown keys
    TemplateOutcome applyBuiltin( QgsLayout *layout, const QString &key );

    // Directory holding <key>.qpt builtins. Resolution order:
    //   1. the last value passed to setTemplatesDir() (empty resets to auto);
    //   2. $PALEO_LAYOUT_TEMPLATES_DIR;
    //   3. first existing "<app dir | ancestor up to 3 levels>/docs/templates".
    // Returns an empty string when nothing resolves — applyBuiltin then fails
    // with "not found" until the dir is set. Tests pin it to the worktree's
    // docs/templates explicitly.
    void setTemplatesDir( const QString &dir );
    QString templatesDir() const;

    // Actions for the shell's File menu.
    QAction *saveAsTemplateAction();
    QAction *loadFromTemplateAction();
    QAction *applyBuiltinAction( const QString &key ); //!< nullptr for unknown keys

    // UI wiring: layout provider consulted by the action handlers only.
    void setLayoutProvider( const std::function<QgsLayout *()> &provider );

  signals:
    void templateFinished( const QString &path, bool ok );

  private:
    TemplateOutcome loadFromFile( QgsLayout *layout, const QString &path );

    QAction *m_saveAction = nullptr;
    QAction *m_loadAction = nullptr;
    std::function<QgsLayout *()> m_layoutProvider;
    QString m_templatesDir;
};
