# Crossplot / unsupervised facies. Existing module targets preserve layering.
target_sources(paleo_algorithms PRIVATE src/algorithms/cluster/cluster.cpp)
add_paleo_test(tst_cluster LIBS paleo_algorithms)
target_sources(paleo_services PRIVATE src/services/crossplotsamples.cpp)
add_paleo_test(tst_crossplot_samples LIBS paleo_services)
target_sources(paleo_ui PRIVATE src/ui/crossplot/crossplotpanel.cpp)
add_paleo_test(tst_crossplotpanel LIBS paleo_ui)
target_sources(paleo_services PRIVATE src/services/faciesclassificationservice.cpp)
target_sources(paleo_workflow PRIVATE src/workflow/faciesclassify.cpp)
add_paleo_test(tst_faciesclassify LIBS paleo_workflow)
target_sources(paleo_services PRIVATE src/services/crossplotsources.cpp)
target_sources(paleo_qgis PRIVATE src/qgis/crossplotmaplink.cpp)
target_sources(paleo_app PRIVATE src/app/crossplotcontroller.cpp)
add_paleo_test(tst_crossplot_perf LIBS paleo_services)
set_tests_properties(tst_crossplot_perf PROPERTIES RUN_SERIAL TRUE)
add_paleo_test(tst_crossplot_controller LIBS paleo_app)
